### ISSUE TITLE
starter button

### ISSUE THREAD

**Issue by bobblkabb** [justleoo/dotfiles#5]
First of all: great design!

Got an issue with the green starter button. Having a box symbol instead of the regular symbol. What did I miss?

**Comment by bobblkabb** [comment]
..it's missing in your template

**Comment by justleoo** [comment]
what do you mean? i'm sorry

**Comment by bobblkabb** [comment]
This:
```
    "custom/void": {
	"format": "",
	"on-click": "wofi --show run"
    },
```

**Comment by justleoo** [comment]
ah yes, do you installed nerd fonts? if yes, and don't worked, try to change the icon on `"format": "new icon here"`
